### ISSUE TITLE
stops creator overpass to many connections

### ISSUE THREAD

**Issue by mvanlaar** [grote/osm2gtfs#69]
When building a stops list i\m getting the following error:

Traceback (most recent call last):
  File "osm2gtfs.py", line 101, in <module>
    main()
  File "osm2gtfs.py", line 67, in main
    stops_creator.add_stops_to_schedule(schedule, data)
  File "C:\Projecten\osm2gtfs\creators\stops_creator.py", line 20, in add_stops_to_schedule
    stops = data.get_stops()
  File "C:\Projecten\osm2gtfs\core\osm_connector.py", line 239, in get_stops
    self._get_names_for_unnamed_stops()
  File "C:\Projecten\osm2gtfs\core\osm_connector.py", line 488, in _get_names_for_unnamed_stops
    self._find_best_name_for_unnamed_stop(stop)
  File "C:\Projecten\osm2gtfs\core\osm_connector.py", line 518, in _find_best_name_for_unnamed_stop
    """ % (stop.lat, stop.lon, stop.lat, stop.lon))
  File "C:\Python27\lib\site-packages\overpy\__init__.py", line 123, in query
    raise exception.OverpassTooManyRequests
overpy.exception.OverpassTooManyRequests: Too many requests

or 

Traceback (most recent call last):
  File "osm2gtfs.py", line 101, in <module>
    main()
  File "osm2gtfs.py", line 67, in main
    stops_creator.add_stops_to_schedule(schedule, data)
  File "C:\Projecten\osm2gtfs\creators\stops_creator.py", line 20, in add_stops_to_schedule
    stops = data.get_stops()
  File "C:\Projecten\osm2gtfs\core\osm_connector.py", line 211, in get_stops
    self._get_names_for_unnamed_stops()
  File "C:\Projecten\osm2gtfs\core\osm_connector.py", line 488, in _get_names_for_unnamed_stops
    self._find_best_name_for_unnamed_stop(stop)
  File "C:\Projecten\osm2gtfs\core\osm_connector.py", line 545, in _find_best_name_for_unnamed_stop
    candidate.get_nodes(resolve_missing=True))
  File "C:\Python27\lib\site-packages\overpy\__init__.py", line 860, in get_nodes
    tmp_result = self._result.api.query(query)
  File "C:\Python27\lib\site-packages\overpy\__init__.py", line 126, in query
    raise exception.OverpassGatewayTimeout
overpy.exception.OverpassGatewayTimeout: Server load too high

Is there a way to avoid it?

**Comment by grote** [comment]
You could use a different API server: http://wiki.openstreetmap.org/wiki/Overpass_API

Or if you have many stops without names in OSM, you could [set `name_auto` to `no`](https://github.com/grote/osm2gtfs/blob/master/creators/fenix/fenix.json#L15) in your config file.

**Comment by mvanlaar** [comment]
where can i configure a different server? is this configurable?

**Comment by grote** [comment]
You need to ask the people from the [overpy library](https://github.com/DinoTools/python-overpy) or look into their source. Their API URL is [defined here](https://github.com/DinoTools/python-overpy/blob/master/overpy/__init__.py#L62).
